### PR TITLE
Render plain-text without quotations

### LINKED ISSUE #99: Rendering text dynamically via {eval} returns single quoted output of strings.
### Describe the bug

**Context**
When rendering strings using {eval}, it returns single quoted text. Integers render as expected (see below).

**Expectation**

The behavior should be more like a normal print, which strips the quotes, e.g.
```python
print("foo") # This is what we should see
print("foo".__repr__()) # This is what a rendered {eval} with a string looks like.
```
**Note**:  integers render as expected given, e.g.

```python
test1 = 12 
test2 = "Test String"
```
....Followed by the following MyST markdown:

```
- Testing an int:   {eval}`test1`
- Testing a string: {eval}`test2`
```
...Renders the following. Notice the quotes around the string variable. 

image

**Version Info.**

Jupyterlab version: 3.6.1
jupyterlab-myst:      1.1.0

### Reproduce the bug

To reproduce, use {eval} with strings vs. ints.

### List your environment

_No response_

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #99 

I'm not hugely familiar with React, so I'm not sure if this fully respects dependencies.

### CODE REVIEW

File: src/inlineExpression.tsx [hunk 1]
```diff
@@ -85,47 +85,79 @@ export class RenderedExpression extends Widget {
...
-  const ref = useRef<HTMLDivElement>(null);
-  const { cell } = useJupyterCell();
-  // Load the information from the MystMarkdownCell
-  const metadata = getUserExpressions(cell);
-  const trusted = cell?.model.trusted ?? false;
-  // We use the notebook rendermime directly
-  const rendermime = (cell?.parent as StaticNotebook).rendermime;
+function PlainTextRenderer({ content }: { content: string }) {
+  content = content.replace(/^(["'])(.*)\1$/, '$2');
+  return <span>{content}</span>;
```
Comment (rowanc1) [inline src/inlineExpression.tsx:90]: We might want this a bit fancier in the future, e.g. style + alt-text hover with the expression used to create it, but for now this is great!

**Comment by rowanc1** [comment]
This looks good to merge in @agoose77 as soon as tests pass -- I know that @fperez was looking for this asap, so we could also consider another patch release.
